name: Test Docker images

on:
  push:
    branches: [main]
    paths:
      - "docker/**"
      - "poetry.lock"
      - "pyproject.toml"
      - "src/backend/**"
      - ".github/workflows/docker_test.yml"

env:
  POETRY_VERSION: "1.8.2"

jobs:
  test-docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    name: Test docker images
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push (latest-dev) image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: docker/build_and_push.Dockerfile
          tags: ghcr.io/OPHoperHPO/langflow:latest-dev
          # provenance: false will result in a single manifest for all platforms which makes the image pullable from arm64 machines via the emulation (e.g. Apple Silicon machines)
          provenance: false
      - name: Build and push (latest-dev) image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: docker/build_and_push.Dockerfile
          tags: ghcr.io/OPHoperHPO/langflow:latest-dev
          # provenance: false will result in a single manifest for all platforms which makes the image pullable from arm64 machines via the emulation (e.g. Apple Silicon machines)
          provenance: false
      - name: Build and push (latest-dev-backend) image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: docker/build_and_push_backend.Dockerfile
          tags: ghcr.io/OPHoperHPO/langflow:latest-dev-backend
          # provenance: false will result in a single manifest for all platforms which makes the image pullable from arm64 machines via the emulation (e.g. Apple Silicon machines)
          provenance: false
          build-args: |
            LANGFLOW_IMAGE=ghcr.io/OPHoperHPO/langflow:latest-dev
      - name: Build and push (latest-dev-frontend) image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: docker/build_and_push_frontend.Dockerfile
          tags: ghcr.io/OPHoperHPO/langflow:latest-dev-frontend
          # provenance: false will result in a single manifest for all platforms which makes the image pullable from arm64 machines via the emulation (e.g. Apple Silicon machines)
          provenance: false
          build-args: |
            LANGFLOW_IMAGE=ghcr.io/OPHoperHPO/langflow:latest-dev
  
